# -*- coding: utf-8 -*-
"""taller_embeddings_salud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vi3AtJ28pMA8JNbHmv2EwUs78L_Q5wHB

# 🧠 Caso de Uso: Salud – Análisis de Registros Médicos

Este notebook demuestra cómo utilizar embeddings y FAISS para analizar similitudes entre registros médicos utilizando un modelo LLM (all-MiniLM-L6-v2).
"""

# Paso 1: Instalar dependencias
!pip install faiss-cpu sentence-transformers

# Paso 2: Importar librerías
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# Paso 3: Datos de ejemplo (registros médicos)
documentos = [
    "Paciente con antecedentes de hipertensión y diabetes tipo 2.",
    "No se detectan anomalías en el ECG, presión arterial normal.",
    "Síntomas persistentes de fatiga y pérdida de peso en el último mes.",
    "El paciente fue diagnosticado con cáncer de pulmón en etapa temprana.",
    "Niveles de glucosa elevados tras el ayuno, posible prediabetes.",
    "Dolor torácico frecuente y dificultad para respirar en las noches.",
    "Historial familiar de enfermedades cardiovasculares y obesidad.",
    "Paciente con tratamiento reciente por anemia ferropénica.",
    "Se observa fiebre persistente y erupciones cutáneas no identificadas.",
    "El paciente reporta dolor abdominal crónico y diarrea intermitente.",
    "Presenta migrañas frecuentes y sensibilidad a la luz.",
    "Revisión médica tras fractura de fémur, evolución favorable.",
    "Dolor en las articulaciones, posiblemente asociado a artritis reumatoide.",
    "Paciente con diagnóstico reciente de enfermedad celíaca.",
    "Reporta insomnio severo y episodios de ansiedad recurrentes.",
    "Síntomas compatibles con infección urinaria aguda.",
    "Paciente con pérdida auditiva progresiva en el oído derecho.",
    "Evaluación de función pulmonar en paciente con asma crónica.",
    "Historial de alergias severas a medicamentos antiinflamatorios.",
    "Examen de sangre revela niveles bajos de plaquetas."
]

# Paso 4: Cargar modelo para embeddings
modelo = SentenceTransformer('all-MiniLM-L6-v2')

# Paso 5: Crear los embeddings
embeddings = modelo.encode(documentos, convert_to_numpy=True)

# Paso 6: Indexar los embeddings con FAISS
dim = embeddings.shape[1]
index = faiss.IndexFlatIP(dim)  # IP = Inner Product (coseno si normalizamos)
faiss.normalize_L2(embeddings)  # normalizamos para usar similitud de coseno
index.add(embeddings)

# Paso 7: Crear una pregunta (consulta)
#consulta = "Paciente con problemas respiratorios y antecedentes oncológicos"
consulta = "Paciente con ojos amarillos"
embedding_consulta = modelo.encode([consulta], convert_to_numpy=True)
faiss.normalize_L2(embedding_consulta)

# Paso 8: Buscar k documentos más similares
k = 3
distancias, indices = index.search(embedding_consulta, k)

# Paso 9: Mostrar resultados
print("Consulta:", consulta)
print("\nRespuestas similares:")
for i, idx in enumerate(indices[0]):
    print(f"{i+1}. {documentos[idx]} (Similitud: {distancias[0][i]:.4f})")